// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZW0NdvM7wSFZtyB1Nas1zAbocIN-e-WQ',
    appId: '1:939363111062:web:0b915aa914ddd656c972b7',
    messagingSenderId: '939363111062',
    projectId: 'blood-buddy-43250',
    authDomain: 'blood-buddy-43250.firebaseapp.com',
    storageBucket: 'blood-buddy-43250.firebasestorage.app',
    measurementId: 'G-3DR123XSN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2vfjdiAG1-YdBqPffC0KdmiX3geqcKM',
    appId: '1:939363111062:android:2bfa688a4db06711c972b7',
    messagingSenderId: '939363111062',
    projectId: 'blood-buddy-43250',
    storageBucket: 'blood-buddy-43250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8FQ0_6aInW9iLwEgrnjNuiuQeFKcgRAw',
    appId: '1:939363111062:ios:c7a0f9f3309c703cc972b7',
    messagingSenderId: '939363111062',
    projectId: 'blood-buddy-43250',
    storageBucket: 'blood-buddy-43250.firebasestorage.app',
    iosBundleId: 'com.example.bloodBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8FQ0_6aInW9iLwEgrnjNuiuQeFKcgRAw',
    appId: '1:939363111062:ios:c7a0f9f3309c703cc972b7',
    messagingSenderId: '939363111062',
    projectId: 'blood-buddy-43250',
    storageBucket: 'blood-buddy-43250.firebasestorage.app',
    iosBundleId: 'com.example.bloodBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZW0NdvM7wSFZtyB1Nas1zAbocIN-e-WQ',
    appId: '1:939363111062:web:ec25a13cdaf9ea10c972b7',
    messagingSenderId: '939363111062',
    projectId: 'blood-buddy-43250',
    authDomain: 'blood-buddy-43250.firebaseapp.com',
    storageBucket: 'blood-buddy-43250.firebasestorage.app',
    measurementId: 'G-JSTHBNPYXW',
  );
}
